VALIDATION_OUTPUT=$(cat ./DEPLOY_ORG.txt) 
DEPLOYMENT_STRING=${VALIDATION_OUTPUT#*Deploy ID: }
# echo $DEPLOYMENT_STRING
FINAL_DEPLOY_ID=${DEPLOYMENT_STRING:0:18}
echo $FINAL_DEPLOY_ID
sfdx force:source:deploy -q $FINAL_DEPLOY_ID -u $SOURCE_ORG_ALIAS